fabric8-analytics/graph-cve-sync

- graph_cve_sync.py
We will delete them next time...
> Do not fail if we cannot delete superfluous CVEs from graph

- openshift/template.yaml
And keep 4 last successful runs around for inspection.
> [openshift] Set failedJobsHistoryLimit to 0

- openshift/template.yaml
Reverts fabric8-analytics/graph-cve-sync#18
> Revert "Update template.yaml"

- detect-dead-code.sh
- graph_cve_sync.py
- graph_snyk_cve_sync.py
- openshift/template.yaml
- requirements.txt
- runtests.sh
- snyk_feed.py
- tests/test_graph_snyk_cve_sync.py
- tests/test_snyk_feed.py
This PR is for the following changes
1. Support mulitple version options from snyk
2. Reduce the ingestion timelines
3. Save the feed in S3 once a week
4. Read and ingest directly from feed
5. Split the ingestion as per the ecosystem
> modified functionality to reduce time. support multiple version cases

- graph_cve_sync.py
Removed code related to "cve_source" field as it is not in use anymore.
Fixes # APPAI-1202
> Removed code related to "cve_source" field.

- graph_snyk_cve_sync.py
- openshift/template.yaml
- snyk_feed.py
- tests/test_graph_snyk_cve_sync.py
> delta feed mode addition

- graph_snyk_cve_sync.py
https://issues.redhat.com/browse/APPAI-1278
> delta feed added at wrong position. was causing incorrect json

- snyk_feed.py
- tests/test_snyk_feed.py
A stop gap solution to start the ingestion today. Will change the code to read the value from env variable
> changing the schedule

- graph_snyk_cve_sync.py
- tests/test_graph_snyk_cve_sync.py
converting all python pkgs to lower case
> fix: Case normalize python package names

- graph_snyk_cve_sync.py
- openshift/template.yaml
- tests/test_graph_snyk_cve_sync.py
instead of checking only the previous day for delta feed, now we can have a handle on having an offset day for picking up data for detla feed mode
> flexible offset value

- .github/workflows/ci-build.yml
- check-docstyle.sh
- detect-common-errors.sh
- detect-dead-code.sh
- measure-cyclomatic-complexity.sh
- measure-maintainability-index.sh
- run-linter.sh
Adds scripts and configurations to enable GitHub actions
> Migrate CI to GitHub Actions

- graph_snyk_cve_sync.py
- requirements.txt
This will make sure that we do not get stuck with packages which do not have any versions or gh links
> Support for non availability of gh links / versions

- graph_snyk_cve_sync.py
- openshift/template.yaml
- snyk_feed.py
Instead of storing 200+ mb of files every week, now it will re write the same file "latest-feed.json"
Versioning will switched off for the same via app sre ticket
> Snyk feed storage strategy changed

- requirements.txt
> Update in the utils version

- openshift/template.yaml
> CronJob to v1

- snyk_feed.py
- Migrated application feed API
- Response from new API is transformed to follow old API JSON format
> Modify application feed APIs

- openshift/template.yaml
- snyk_feed.py
> Add ORG_ID as a secret

- snyk_feed.py
> chore: Update API response

- openshift/template.yaml
> Fix snyk url in template

- snyk_feed.py
> Add more log messages

- snyk_feed.py
> Delete unused objects and reduce snyk feed size

- snyk_feed.py
> Remove golang data for testing

- snyk_feed.py
> Add golang empty data in snyk feed

- vulnerability_metadata.py
> [Testing] Initialize json data

- vulnerability_metadata.py
Reverts fabric8-analytics/graph-cve-sync#95
> Revert "[Testing] Initialize json data"

- requirements.txt
- snyk_feed.py
> Test only golang package

- graph_snyk_cve_sync.py
> Rename 'hashesRange' key to 'vulnerableHashRanges'

- requirements.txt
- snyk_feed.py
> Code Cleanup

- openshift/template.yaml
Changing concurrencyPolicy to "Forbid"
Signed-Off-By: Vinagarw@redhat.com
> Changing value of concurrencyPolicy to "Forbid"

- .github/workflows/ci-build.yml
- requirements.txt
- Old Python version failing to setup
> Update python version to 3.10
